zookeeper:
  image: confluent/zookeeper
  container_name: zookeeper
  ports:
    - "2181:2181"
kafka:
  image: confluent/kafka
  container_name: kafka
  ports:
    - "9092:9092"
  links:
    - zookeeper:zookeeper
schema-registry:
  image: confluent/schema-registry
  container_name: schema-registry
  ports:
    - "8081:8081"
  links:
    - zookeeper:zookeeper
    - kafka:kafka
rest-proxy:
  image: confluent/rest-proxy
  container_name: rest-proxy
  ports:
    - "8082:8082"
  links:
    - zookeeper:zookeeper
    - kafka:kafka
    - schema-registry:schema-registry
